package ichorgo

import "time"

// demoArgoCD is the Argo CD of the built-in demo cluster, in every state the app shows: a sync
// running through its waves, a degraded app whose pod crash-loops, an app drifting with
// auto-sync paused, a failed sync, and apps generated by an ApplicationSet.
func demoArgoCD(now time.Time) argoStatus {
	ms := func(d time.Duration) int64 { return now.Add(-d).UnixMilli() }
	infra := &argoOwner{Kind: "ApplicationSet", Name: "infra"}
	auto := argoAuto{Enabled: true, Prune: true}
	helm := func(repo, chart, version string) []argoSrc {
		return []argoSrc{{Repo: repo, Chart: chart, TargetRevision: version}}
	}
	git := func(path string) []argoSrc {
		return []argoSrc{{Repo: "https://git.example.com/homelab/gitops.git", Path: path, TargetRevision: "main"}}
	}
	res := func(kind, ns, name, sync, health string, wave int, result string) argoResource {
		group := ""
		switch kind {
		case "Deployment", "StatefulSet", "DaemonSet":
			group = "apps"
		case "CustomResourceDefinition":
			group = "apiextensions.k8s.io"
		case "Job":
			group = "batch"
		}

		return argoResource{Group: group, Kind: kind, Namespace: ns, Name: name, Sync: sync, Health: health, Wave: wave, SyncResult: result}
	}
	hist := func(id int64, rev, target, chart string, ago time.Duration) argoHistory {
		return argoHistory{ID: id, Revision: rev, TargetRevision: target, Chart: chart, DeployedAt: ms(ago), InitiatedBy: "automated"}
	}
	done := func(revision string, ago time.Duration, total int) *argoOperation {
		return &argoOperation{Phase: "Succeeded", Message: "successfully synced (all tasks run)", StartedAt: ms(ago + 40*time.Second), FinishedAt: ms(ago),
			InitiatedBy: "automated", Revision: revision, Done: total, Total: total, Waves: []int{0}, Failed: []argoResult{}}
	}

	var crashing []kubePod
	for _, p := range demoPods() {
		if !p.Healthy && p.Namespace == "demo" {
			crashing = append(crashing, p)
		}
	}

	apps := []argoApp{
		{
			Namespace: "argocd", Name: "demo-worker", Project: "apps", Level: healthCritical,
			Health: "Degraded", HealthMessage: "Deployment \"worker\" exceeded its progress deadline", Sync: "Synced", Revision: "4be1d0c9f2a7e3b18c6d5a0f9e8b7c6d5a4f3e2d",
			Sources: git("apps/worker"), Destination: argoDest{Server: "https://kubernetes.default.svc", Namespace: "demo"}, AutoSync: argoAuto{Enabled: true, SelfHeal: true},
			SyncOptions: []string{"CreateNamespace=true"}, Operation: done("4be1d0c9f2a7e3b18c6d5a0f9e8b7c6d5a4f3e2d", 3*time.Hour, 3), Conditions: []argoCondition{},
			Resources: []argoResource{
				res("ConfigMap", "demo", "worker-config", "Synced", "", 0, "Synced"),
				res("Service", "demo", "worker", "Synced", "Healthy", 0, "Synced"),
				res("Deployment", "demo", "worker", "Synced", "Degraded", 0, "Synced"),
			},
			History: []argoHistory{hist(12, "4be1d0c9f2a7e3b18c6d5a0f9e8b7c6d5a4f3e2d", "main", "", 3*time.Hour), hist(11, "91c0a7e6d5b4c3a29180f7e6d5c4b3a291807f6e", "main", "", 50*time.Hour)},
			Images:  []string{"busybox:1.37"}, ExternalURLs: []string{}, UnhealthyPods: crashing, ReconciledAt: ms(time.Minute),
		},
		{
			Namespace: "argocd", Name: "grafana", Project: "infra", Owner: infra, Level: healthCritical, Icon: "grafana",
			Health: "Healthy", Sync: "OutOfSync", Revision: "8.5.2",
			Sources: helm("https://grafana.github.io/helm-charts", "grafana", "8.6.0"), Destination: argoDest{Server: "https://kubernetes.default.svc", Namespace: "monitoring"}, AutoSync: auto,
			SyncOptions: []string{"ServerSideApply=true"},
			Operation: &argoOperation{Phase: "Failed", Message: "one or more objects failed to apply, reason: Deployment.apps \"grafana\" is invalid: spec.template.spec.containers[0].image: Required value",
				StartedAt: ms(9 * time.Minute), FinishedAt: ms(8 * time.Minute), InitiatedBy: "automated", Revision: "8.6.0", RetryCount: 5, Done: 3, Total: 4, Waves: []int{0},
				Failed: []argoResult{{Kind: "Deployment", Namespace: "monitoring", Name: "grafana", Message: "Deployment.apps \"grafana\" is invalid: spec.template.spec.containers[0].image: Required value"}}},
			Conditions: []argoCondition{{Type: "SyncError", Message: "Failed sync attempt to 8.6.0: one or more objects failed to apply (retried 5 times)."}},
			Resources: []argoResource{
				res("Secret", "monitoring", "grafana", "Synced", "", 0, "Synced"),
				res("ConfigMap", "monitoring", "grafana", "Synced", "", 0, "Synced"),
				res("Service", "monitoring", "grafana", "Synced", "Healthy", 0, "Synced"),
				res("Deployment", "monitoring", "grafana", "OutOfSync", "Healthy", 0, "SyncFailed"),
			},
			History: []argoHistory{hist(31, "8.5.2", "8.5.2", "grafana", 12*24*time.Hour), hist(30, "8.5.1", "8.5.1", "grafana", 30*24*time.Hour)},
			Images:  []string{"grafana/grafana:11.4.0"}, ExternalURLs: []string{"https://grafana.homelab.lan"}, UnhealthyPods: []kubePod{}, ReconciledAt: ms(2 * time.Minute),
		},
		{
			Namespace: "argocd", Name: "longhorn", Project: "infra", Owner: infra, Level: healthWarning, Icon: "longhorn",
			Health: "Progressing", HealthMessage: "Waiting for rollout to finish: 1 of 3 updated pods are available", Sync: "OutOfSync", Revision: "1.12.0",
			Sources: helm("https://charts.longhorn.io", "longhorn", "1.12.1"), Destination: argoDest{Server: "https://kubernetes.default.svc", Namespace: "longhorn-system"}, AutoSync: auto,
			SyncOptions: []string{"ServerSideApply=true"},
			Operation: &argoOperation{Phase: "Running", Message: "waiting for healthy state of apps/DaemonSet/longhorn-manager", StartedAt: ms(95 * time.Second),
				InitiatedBy: "automated", Revision: "1.12.1", Done: 5, Total: 9, Wave: 1, Waves: []int{-1, 0, 1, 2}, Failed: []argoResult{}},
			Conditions: []argoCondition{},
			Resources: []argoResource{
				res("CustomResourceDefinition", "", "volumes.longhorn.io", "Synced", "", -1, "Synced"),
				res("CustomResourceDefinition", "", "engines.longhorn.io", "Synced", "", -1, "Synced"),
				res("ServiceAccount", "longhorn-system", "longhorn-service-account", "Synced", "", 0, "Synced"),
				res("ConfigMap", "longhorn-system", "longhorn-default-setting", "Synced", "", 0, "Synced"),
				res("Service", "longhorn-system", "longhorn-frontend", "Synced", "Healthy", 0, "Synced"),
				res("DaemonSet", "longhorn-system", "longhorn-manager", "OutOfSync", "Progressing", 1, ""),
				res("Deployment", "longhorn-system", "longhorn-driver-deployer", "OutOfSync", "Healthy", 1, ""),
				res("Deployment", "longhorn-system", "longhorn-ui", "OutOfSync", "Healthy", 2, ""),
				res("Job", "longhorn-system", "longhorn-post-upgrade", "OutOfSync", "", 2, ""),
			},
			History: []argoHistory{hist(18, "1.12.0", "1.12.0", "longhorn", 21*24*time.Hour), hist(17, "1.11.2", "1.11.2", "longhorn", 60*24*time.Hour)},
			Images:  []string{"longhornio/longhorn-manager:v1.12.0", "longhornio/longhorn-ui:v1.12.0"}, ExternalURLs: []string{}, UnhealthyPods: []kubePod{}, ReconciledAt: ms(10 * time.Second),
		},
		{
			Namespace: "argocd", Name: "cert-manager", Project: "infra", Level: healthWarning, Icon: "cert-manager",
			Health: "Healthy", Sync: "OutOfSync", Revision: "v1.18.2",
			Sources: helm("https://charts.jetstack.io", "cert-manager", "v1.19.0"), Destination: argoDest{Server: "https://kubernetes.default.svc", Namespace: "cert-manager"},
			SyncOptions: []string{"CreateNamespace=true", "ServerSideApply=true"}, Operation: done("v1.18.2", 6*24*time.Hour, 5), Conditions: []argoCondition{},
			Resources: []argoResource{
				res("CustomResourceDefinition", "", "certificates.cert-manager.io", "OutOfSync", "", -2, ""),
				res("Deployment", "cert-manager", "cert-manager", "OutOfSync", "Healthy", 0, ""),
				res("Deployment", "cert-manager", "cert-manager-webhook", "OutOfSync", "Healthy", 0, ""),
				res("Service", "cert-manager", "cert-manager-webhook", "Synced", "Healthy", 0, ""),
				{Kind: "ConfigMap", Namespace: "cert-manager", Name: "cert-manager-legacy", Sync: "OutOfSync", Prune: true},
			},
			History: []argoHistory{hist(9, "v1.18.2", "v1.18.2", "cert-manager", 6*24*time.Hour), hist(8, "v1.18.1", "v1.18.1", "cert-manager", 40*24*time.Hour), hist(7, "v1.17.4", "v1.17.4", "cert-manager", 90*24*time.Hour)},
			Images:  []string{"quay.io/jetstack/cert-manager-controller:v1.18.2"}, ExternalURLs: []string{}, UnhealthyPods: []kubePod{}, ReconciledAt: ms(3 * time.Minute),
		},
		{
			Namespace: "argocd", Name: "cilium", Project: "infra", Owner: infra, Level: healthOK, Icon: "cilium",
			Health: "Healthy", Sync: "Synced", Revision: "1.18.2",
			Sources: helm("https://helm.cilium.io", "cilium", "1.18.2"), Destination: argoDest{Server: "https://kubernetes.default.svc", Namespace: "kube-system"}, AutoSync: auto,
			SyncOptions: []string{"ServerSideApply=true"}, Operation: done("1.18.2", 4*24*time.Hour, 3), Conditions: []argoCondition{},
			Resources: []argoResource{
				res("ConfigMap", "kube-system", "cilium-config", "Synced", "", 0, "Synced"),
				res("DaemonSet", "kube-system", "cilium", "Synced", "Healthy", 0, "Synced"),
				res("Deployment", "kube-system", "cilium-operator", "Synced", "Healthy", 0, "Synced"),
			},
			History: []argoHistory{hist(22, "1.18.2", "1.18.2", "cilium", 4*24*time.Hour), hist(21, "1.18.1", "1.18.1", "cilium", 25*24*time.Hour)},
			Images:  []string{"quay.io/cilium/cilium:v1.18.2"}, ExternalURLs: []string{}, UnhealthyPods: []kubePod{}, ReconciledAt: ms(30 * time.Second),
		},
		{
			Namespace: "argocd", Name: "traefik", Project: "infra", Owner: infra, Level: healthOK, Icon: "traefik",
			Health: "Healthy", Sync: "Synced", Revision: "37.1.1",
			Sources: helm("https://traefik.github.io/charts", "traefik", "37.1.1"), Destination: argoDest{Server: "https://kubernetes.default.svc", Namespace: "traefik"}, AutoSync: auto,
			SyncOptions: []string{}, Operation: done("37.1.1", 9*24*time.Hour, 2), Conditions: []argoCondition{},
			Resources: []argoResource{
				res("Service", "traefik", "traefik", "Synced", "Healthy", 0, "Synced"),
				res("Deployment", "traefik", "traefik", "Synced", "Healthy", 0, "Synced"),
			},
			History: []argoHistory{hist(14, "37.1.1", "37.1.1", "traefik", 9*24*time.Hour)},
			Images:  []string{"traefik:v3.5.3"}, ExternalURLs: []string{"https://traefik.homelab.lan/dashboard/"}, UnhealthyPods: []kubePod{}, ReconciledAt: ms(40 * time.Second),
		},
		{
			Namespace: "argocd", Name: "hello-ichor", Project: "apps", Level: healthOK,
			Health: "Healthy", Sync: "Synced", Revision: "4be1d0c9f2a7e3b18c6d5a0f9e8b7c6d5a4f3e2d",
			Sources: git("apps/hello-ichor"), Destination: argoDest{Server: "https://kubernetes.default.svc", Namespace: "demo"}, AutoSync: argoAuto{Enabled: true, Prune: true, SelfHeal: true},
			SyncOptions: []string{"CreateNamespace=true"}, Operation: done("4be1d0c9f2a7e3b18c6d5a0f9e8b7c6d5a4f3e2d", 3*time.Hour, 2), Conditions: []argoCondition{},
			Resources: []argoResource{
				res("Service", "demo", "hello-ichor", "Synced", "Healthy", 0, "Synced"),
				res("Deployment", "demo", "hello-ichor", "Synced", "Healthy", 0, "Synced"),
			},
			History: []argoHistory{hist(5, "4be1d0c9f2a7e3b18c6d5a0f9e8b7c6d5a4f3e2d", "main", "", 3*time.Hour)},
			Images:  []string{"nginx:1.27"}, ExternalURLs: []string{"https://hello.homelab.lan"}, UnhealthyPods: []kubePod{}, ReconciledAt: ms(time.Minute),
		},
		{
			Namespace: "argocd", Name: "nightly-reports", Project: "apps", Level: healthIdle,
			Health: "Suspended", HealthMessage: "CronJob is suspended", Sync: "Synced", Revision: "4be1d0c9f2a7e3b18c6d5a0f9e8b7c6d5a4f3e2d",
			Sources: git("apps/nightly-reports"), Destination: argoDest{Server: "https://kubernetes.default.svc", Namespace: "reports"}, AutoSync: auto,
			SyncOptions: []string{}, Operation: done("4be1d0c9f2a7e3b18c6d5a0f9e8b7c6d5a4f3e2d", 3*time.Hour, 1), Conditions: []argoCondition{},
			Resources: []argoResource{{Group: "batch", Kind: "CronJob", Namespace: "reports", Name: "nightly-reports", Sync: "Synced", Health: "Suspended", SyncResult: "Synced"}},
			History:   []argoHistory{hist(3, "4be1d0c9f2a7e3b18c6d5a0f9e8b7c6d5a4f3e2d", "main", "", 3*time.Hour)},
			Images:    []string{}, ExternalURLs: []string{}, UnhealthyPods: []kubePod{}, ReconciledAt: ms(time.Minute),
		},
	}

	out := mapArgoCD(nil, nil, nil)
	out.Version = "v3.4.5"
	out.Apps = apps
	out.AppSets = []argoAppSet{
		{Namespace: "argocd", Name: "infra", Level: healthCritical, Apps: 4, Conditions: []argoAppSetCondition{
			{Type: "ErrorOccurred", Status: "False", Message: "Successfully generated parameters for all Applications"},
			{Type: "ResourcesUpToDate", Status: "True", Message: "ApplicationSet up to date"},
		}},
	}
	out.Projects = []argoProject{
		{Namespace: "argocd", Name: "apps", Description: "Self-hosted applications"},
		{Namespace: "argocd", Name: "infra", Description: "Cluster infrastructure", SyncWindows: 1},
	}

	return out
}
