import SwiftUI
import IchorCore

/// The Argo CD apps of the chosen chip, grouped, each opening its screen: swipe right to sync
/// (through the sync sheet), left to refresh; in selection mode, ticks for the bottom bar.
struct ArgoAppsList: View {
    let status: ArgoStatus
    @Binding var filter: ArgoFilter
    let grouping: ArgoGrouping
    let query: String
    let downNodes: Set<String>
    @Binding var selection: Set<String>
    /// Apps an action is being sent to.
    let busy: Set<String>
    let refresh: () async -> Void
    let onSync: (ArgoApp) -> Void
    let onRefresh: (ArgoApp) -> Void
    /// "Sync all out of sync": the apps to confirm.
    let onSyncAll: ([ArgoApp]) -> Void

    var body: some View {
        let shown = filterArgoApps(status.apps, filter: filter, query: query)
        let candidates = syncAllCandidates(shown)
        List(selection: $selection) {
            if filter == .outOfSync && !candidates.isEmpty {
                Section {
                    Button { onSyncAll(candidates) } label: {
                        Label(String(localized: "Sync all out of sync (\(candidates.count))"), systemImage: "arrow.triangle.2.circlepath")
                    }
                }
            }
            ForEach(groupArgoApps(shown, by: grouping)) { group in
                Section {
                    ForEach(group.apps) { app in
                        NavigationLink(value: ArgoAppRoute(namespace: app.namespace, name: app.name, downNodes: downNodes)) {
                            ArgoAppRow(app: app, downNodes: downNodes, busy: busy.contains(app.id))
                        }
                        .swipeActions(edge: .leading) {
                            Button { onSync(app) } label: { Label("Sync", systemImage: "arrow.triangle.2.circlepath") }
                                .tint(.blue)
                                .disabled(!app.canSync)
                        }
                        .swipeActions(edge: .trailing) {
                            Button { onRefresh(app) } label: { Label("Refresh", systemImage: "arrow.clockwise") }
                                .tint(.indigo)
                        }
                    }
                } header: {
                    if grouping != .none { groupHeader(group) }
                }
            }
        }
        .overlay {
            if shown.isEmpty {
                if !query.isEmpty {
                    ContentUnavailableView.search(text: query)
                } else if filter != .all {
                    ContentUnavailableView {
                        Label("Nothing here", systemImage: "checkmark.circle")
                    } description: {
                        Text("No app matches “\(filter.label)”.")
                    } actions: {
                        Button("Show all") { filter = .all }
                    }
                } else {
                    ContentUnavailableView("No Argo CD apps", systemImage: "arrow.triangle.branch")
                }
            }
        }
        .refreshable { await refresh() }
        .themedBackground()
    }

    private func groupHeader(_ group: ArgoGroup) -> some View {
        HStack {
            Text(verbatim: group.title.isEmpty ? noGroupTitle : group.title)
            Spacer()
            Text(verbatim: "\(group.apps.count)").monospacedDigit()
        }
    }

    private var noGroupTitle: String {
        switch grouping {
        case .appSet: String(localized: "Not generated by an ApplicationSet")
        case .namespace: String(localized: "No namespace")
        default: String(localized: "Other")
        }
    }
}

/// Icon, name and owner, "chart@version · 3 h ago" or where a sync stands, the likely cause of a
/// problem, and the health and sync glyphs.
struct ArgoAppRow: View {
    let app: ArgoApp
    let downNodes: Set<String>
    var busy = false

    var body: some View {
        HStack(spacing: 12) {
            AppIconView(app: app.iconApp, size: 40)
            VStack(alignment: .leading, spacing: 3) {
                HStack(spacing: 6) {
                    Text(verbatim: app.name).font(.body.weight(.medium)).lineLimit(1)
                    if let owner = app.owner { ArgoOwnerBadge(owner: owner) }
                }
                Text(verbatim: detail)
                    .font(.caption.monospacedDigit())
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
                    .truncationMode(.middle)
                if let op = app.operation, op.phase.active {
                    HStack(spacing: 6) {
                        Text(verbatim: [op.phase.label, argoProgressText(op)].filter { !$0.isEmpty }.joined(separator: " · "))
                            .font(.caption.weight(.medium))
                            .foregroundStyle(.blue)
                            .monospacedDigit()
                        if op.total > 0 {
                            ProgressView(value: Double(op.done), total: Double(op.total)).frame(maxWidth: 80).tint(.blue)
                        }
                    }
                } else if let cause = app.likelyCause(downNodes: downNodes) {
                    Text(verbatim: cause.text)
                        .font(.caption)
                        .foregroundStyle(app.level.color)
                        .lineLimit(2)
                }
            }
            Spacer(minLength: 4)
            if busy {
                ProgressView()
            } else {
                ArgoGlyphs(health: app.health, sync: app.sync, running: app.isRunning)
            }
        }
        .padding(.vertical, 2)
    }

    private var detail: String {
        var parts = [app.revisionLabel]
        if app.deployedAt > 0 { parts.append(relativeTime(app.deployedAt)) }
        if !app.autoSync.enabled { parts.append(String(localized: "auto-sync off")) }
        if !app.refreshing.isEmpty { parts.append(String(localized: "refreshing…")) }
        return parts.filter { !$0.isEmpty }.joined(separator: " · ")
    }
}

/// The ApplicationSets with their generated apps rolled up (worst first), and the projects.
struct ArgoAppSetsList: View {
    let status: ArgoStatus
    let query: String
    let downNodes: Set<String>
    let refresh: () async -> Void

    var body: some View {
        let q = query.trimmingCharacters(in: .whitespaces)
        let sets = status.appSets.filter { q.isEmpty || $0.name.localizedCaseInsensitiveContains(q) }
        let projects = status.projects.filter { q.isEmpty || $0.name.localizedCaseInsensitiveContains(q) }
        List {
            if !status.appSetsError.isEmpty { Section { ErrorLine(error: status.appSetsError) } }
            Section("ApplicationSets") {
                if sets.isEmpty { Text("No ApplicationSets.").foregroundStyle(.secondary) }
                ForEach(sets) { set in
                    DisclosureGroup {
                        let apps = status.apps(of: set)
                        if apps.isEmpty { Text("No apps generated.").font(.callout).foregroundStyle(.secondary) }
                        ForEach(apps) { app in
                            NavigationLink(value: ArgoAppRoute(namespace: app.namespace, name: app.name, downNodes: downNodes)) {
                                HStack(spacing: 10) {
                                    AppIconView(app: app.iconApp, size: 28)
                                    Text(verbatim: app.name).font(.callout)
                                    Spacer()
                                    ArgoGlyphs(health: app.health, sync: app.sync, running: app.isRunning, font: .caption)
                                }
                            }
                        }
                    } label: {
                        appSetLabel(set)
                    }
                }
            }
            Section("Projects") {
                if projects.isEmpty { Text("No projects.").foregroundStyle(.secondary) }
                ForEach(projects) { project in
                    VStack(alignment: .leading, spacing: 2) {
                        HStack {
                            Text(verbatim: project.name).font(.callout.weight(.medium))
                            Spacer()
                            Text("\(status.apps(of: project).count) apps").font(.caption).foregroundStyle(.secondary).monospacedDigit()
                        }
                        if !project.description.isEmpty {
                            Text(verbatim: project.description).font(.caption).foregroundStyle(.secondary)
                        }
                        if project.syncWindows > 0 {
                            Label(String(localized: "\(project.syncWindows) sync windows"), systemImage: "calendar.badge.clock")
                                .font(.caption)
                                .foregroundStyle(attentionColor)
                        }
                    }
                }
            }
        }
        .refreshable { await refresh() }
        .themedBackground()
    }

    private func appSetLabel(_ set: ArgoAppSet) -> some View {
        HStack(alignment: .top, spacing: 12) {
            HealthDot(health: set.level).padding(.top, 5)
            VStack(alignment: .leading, spacing: 2) {
                Text(verbatim: set.name).font(.callout.weight(.medium))
                Text("\(set.apps) apps").font(.caption).foregroundStyle(.secondary).monospacedDigit()
                if let error = set.error {
                    Text(verbatim: error).font(.caption).foregroundStyle(.red).lineLimit(3)
                }
            }
        }
    }
}
