#!/usr/bin/env python3
"""Fails when the Go core has a function nothing reaches, the Android and iOS apps included.

`deadcode -test` only sees Go callers, so every gomobile entry point looks unreachable. This
script lists the exported functions and methods of go/ichorgo the apps call (Kotlin
`Ichorgo.foo(`, Swift `IchorgoFoo(`, a method as `.foo(` or `::foo`), declares them as
roots in a temporary test file, runs deadcode, then removes the file. What it still reports
has no caller anywhere: delete it, or call it.
"""
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GO = ROOT / "go"
PACKAGE = GO / "ichorgo"
ROOTS = PACKAGE / "zz_mobile_roots_test.go"
# The version go.mod pins for golang.org/x/tools, used when deadcode is not installed.
DEADCODE = "golang.org/x/tools/cmd/deadcode@v0.51.0"

FUNC = re.compile(r"^func (?:\(\w+ \*?(\w+)\) )?([A-Z]\w*)\(", re.MULTILINE)


def sources(directory: Path, suffix: str) -> str:
    return "\n".join(p.read_text(errors="ignore") for p in directory.rglob(f"*{suffix}"))


def lower_first(name: str) -> str:
    return name[0].lower() + name[1:]


def mobile_roots() -> list[str]:
    """Go expressions naming every exported function or method the apps call."""
    kotlin = sources(ROOT / "app/src/main", ".kt")
    swift = sources(ROOT / "ios", ".swift")
    roots = set()
    for path in PACKAGE.glob("*.go"):
        if path.name.endswith("_test.go"):
            continue
        for receiver, name in FUNC.findall(path.read_text()):
            lower = lower_first(name)
            if receiver:
                # Methods of the handles the apps hold (runs, sessions): called by name on them.
                pattern = rf"(\.|::){lower}\b"
                if re.search(pattern, kotlin) or re.search(pattern, swift):
                    roots.add(f"(*{receiver}).{name}")
            elif re.search(rf"Ichorgo\.{lower}\(", kotlin) or re.search(rf"Ichorgo{name}\(", swift):
                roots.add(name)
    return sorted(roots)


def deadcode_command() -> list[str]:
    found = shutil.which("deadcode")
    if not found:
        gobin = subprocess.run(["go", "env", "GOBIN"], capture_output=True, text=True, cwd=GO).stdout.strip()
        gopath = subprocess.run(["go", "env", "GOPATH"], capture_output=True, text=True, cwd=GO).stdout.strip()
        for directory in filter(None, [gobin, os.path.join(gopath, "bin") if gopath else ""]):
            candidate = Path(directory) / "deadcode"
            if candidate.is_file():
                found = str(candidate)
                break
    return [found] if found else ["go", "run", DEADCODE]


def main() -> int:
    roots = mobile_roots()
    body = "\n".join(f"\t{root}," for root in roots)
    ROOTS.write_text(
        "// Code generated by scripts/deadcode.py; DO NOT EDIT. Removed once deadcode ran.\n\n"
        "package ichorgo\n\n"
        "// What the Android and iOS apps call through gomobile: roots for deadcode.\n"
        f"var _ = []any{{\n{body}\n}}\n"
    )
    try:
        result = subprocess.run(deadcode_command() + ["-test", "./..."], capture_output=True, text=True, cwd=GO)
    finally:
        ROOTS.unlink(missing_ok=True)
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        return result.returncode
    unreachable = result.stdout.strip()
    if unreachable:
        print(unreachable)
        print(f"\n{len(unreachable.splitlines())} unreachable from Go tests and from the apps ({len(roots)} app entry points).")
        return 1
    print(f"deadcode OK: nothing unreachable ({len(roots)} app entry points).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
