#!/usr/bin/env python3
"""Lists the third-party code linked into the apps, for their "Open-source licenses" screens.

Android (default): declares the Go core's modules to the AboutLibraries Gradle plugin.

Gradle cannot see inside the gomobile AAR, so the "Open-source licenses" screen would only list
the Android dependencies. This lists every module actually linked into the Android Go core
(`go list -deps` for the bound package, with the Android build constraints), detects each one's
license from its LICENSE/COPYING file in the module cache, and writes one library definition per
module, plus one for the Go standard library:

  app/aboutlibraries/libraries/go-<module>.json   (gitignored, regenerated by build.sh)

iOS (--ios OUT): writes one JSON file the app bundles, with the license texts themselves (iOS has
no AboutLibraries): the project's NOTICE and LICENSE, every Go module linked into the iOS Go core
(iOS build constraints), the Go standard library, and the Swift packages checked out by Xcode
(--swift-checkouts, versions from --swift-resolved, Package.resolved).

Fails when a license cannot be recognised, so a new dependency is never listed without its
license.

Usage: scripts/go-licenses.py
       scripts/go-licenses.py --ios ios/Ichor/licenses.json \
           --swift-checkouts ios/build/SourcePackages/checkouts --swift-resolved <Package.resolved>
"""
import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GO_DIR = ROOT / "go"
OUT = ROOT / "app/aboutlibraries/libraries"
PREFIX = "go-"
# The bound package, plus the gobind runtime gomobile links next to it.
PACKAGES = ["./ichorgo", "golang.org/x/mobile/bind/seq"]
ANDROID_ENV = {"GOOS": "android", "GOARCH": "arm64", "CGO_ENABLED": "1"}
IOS_ENV = {"GOOS": "ios", "GOARCH": "arm64", "CGO_ENABLED": "1"}
LICENSE_FILES = re.compile(r"^(LICEN[CS]E|COPYING)(\.md|\.txt|\.mit)?$", re.IGNORECASE)  # LICENSE.MIT: go-errors/errors

# SPDX id -> phrases that must all appear in the license text (whitespace-normalised, lowercase).
# Order matters: the first match wins, so the more specific BSD-3 precedes BSD-2.
SIGNATURES = [
    ("Apache-2.0", ["apache license", "version 2.0"]),
    ("MPL-2.0", ["mozilla public license", "version 2.0"]),
    ("BSD-3-Clause", ["redistribution and use in source and binary forms", "to endorse or promote products derived"]),
    ("BSD-2-Clause", ["redistribution and use in source and binary forms"]),
    ("MIT", ["permission is hereby granted, free of charge"]),
    ("ISC", ["permission to use, copy, modify, and/or distribute this software for any purpose"]),
]


def go(*args: str, env: dict = ANDROID_ENV) -> str:
    env = {**os.environ, **env}
    return subprocess.run(["go", *args], cwd=GO_DIR, env=env, check=True, capture_output=True, text=True).stdout


def linked_modules(env: dict = ANDROID_ENV) -> list[dict]:
    template = "{{with .Module}}{{if not .Main}}{{.Path}}\t{{.Version}}\t{{.Dir}}{{end}}{{end}}"
    rows = {line for line in go("list", "-deps", "-f", template, *PACKAGES, env=env).splitlines() if line}
    modules = [dict(zip(("path", "version", "dir"), row.split("\t"))) for row in rows]
    return sorted(modules, key=lambda m: m["path"])


def license_texts(directory: Path) -> list[str]:
    return [f.read_text(errors="replace") for f in sorted(directory.iterdir()) if f.is_file() and LICENSE_FILES.match(f.name)]


def identify(text: str) -> str | None:
    normalised = " ".join(text.lower().split())
    return next((spdx for spdx, phrases in SIGNATURES if all(p in normalised for p in phrases)), None)


def detect_licenses(module_dir: Path) -> list[str]:
    found = []
    for spdx in map(identify, license_texts(module_dir)):
        if spdx and spdx not in found:
            found.append(spdx)
    return found


def source_url(path: str) -> str:
    if path.startswith("golang.org/x/"):
        return "https://cs.opensource.google/go/x/" + path.removeprefix("golang.org/x/").split("/")[0]
    return "https://pkg.go.dev/" + path


def definition(module: dict, licenses: list[str]) -> dict:
    return {
        "uniqueId": module["path"],
        "artifactVersion": module["version"],
        "name": module["path"],
        "description": "Go module compiled into the app's core library.",
        "website": source_url(module["path"]),
        "licenses": licenses,
    }


def stdlib_definition() -> dict:
    return {
        "uniqueId": "go.dev/std",
        "artifactVersion": go("env", "GOVERSION").strip().removeprefix("go"),
        "name": "Go standard library",
        "description": "The Go runtime and standard library, compiled into the app's core library.",
        "website": "https://go.dev",
        "organization": {"name": "The Go Authors", "url": "https://go.dev"},
        "licenses": ["BSD-3-Clause"],
    }


def file_name(path: str) -> str:
    return PREFIX + re.sub(r"[^A-Za-z0-9]+", "-", path).strip("-").lower() + ".json"


def library(name: str, version: str, website: str, directory: Path) -> dict | None:
    """One iOS entry with the full license texts; None when no license is recognised."""
    texts = license_texts(directory)
    licenses = detect_licenses(directory)
    if not licenses:
        return None
    return {"name": name, "version": version, "website": website, "licenses": licenses,
            "text": "\n\n".join(t.strip() for t in texts)}


def swift_pins(resolved: Path | None) -> dict[str, dict]:
    """Package.resolved (v1 to v3) pins by lowercase identity: version and repository URL."""
    if not resolved or not resolved.exists():
        return {}
    data = json.loads(resolved.read_text())
    pins = data.get("pins") or data.get("object", {}).get("pins", [])
    by_identity = {}
    for pin in pins:
        location = pin.get("location") or pin.get("repositoryURL", "")
        identity = (pin.get("identity") or pin.get("package") or location.rstrip("/").split("/")[-1]).lower()
        state = pin.get("state", {})
        by_identity[identity.removesuffix(".git")] = {
            "version": state.get("version") or state.get("revision", "")[:12],
            "website": location.removesuffix(".git"),
        }
    return by_identity


def swift_libraries(checkouts: Path, resolved: Path | None, unknown: list[str]) -> list[dict]:
    pins = swift_pins(resolved)
    libraries = []
    for directory in sorted(p for p in checkouts.iterdir() if p.is_dir()):
        pin = pins.get(directory.name.lower(), {"version": "", "website": ""})
        entry = library(directory.name, pin["version"], pin["website"], directory)
        if entry:
            libraries.append(entry)
        else:
            unknown.append(directory.name)
    return libraries


def ios_licenses(swift_checkouts: Path | None, swift_resolved: Path | None) -> tuple[dict, list[str]]:
    """The iOS licenses file and the dependencies whose license was not recognised."""
    unknown: list[str] = []
    libraries = []
    for module in linked_modules(IOS_ENV):
        entry = library(module["path"], module["version"], source_url(module["path"]), Path(module["dir"]))
        if entry:
            libraries.append(entry)
        else:
            unknown.append(module["path"])
    goroot = Path(go("env", "GOROOT", env=IOS_ENV).strip())
    std = library("Go standard library", go("env", "GOVERSION", env=IOS_ENV).strip().removeprefix("go"),
                  "https://go.dev", goroot)
    libraries.append(std) if std else unknown.append("Go standard library")
    if swift_checkouts:
        libraries.extend(swift_libraries(swift_checkouts, swift_resolved, unknown))
    notice = "\n\n".join((ROOT / name).read_text().strip() for name in ("NOTICE", "LICENSE"))
    libraries.sort(key=lambda entry: entry["name"].lower())
    return {"notice": notice, "libraries": libraries}, unknown


def write_ios(out: Path, swift_checkouts: Path | None, swift_resolved: Path | None) -> int:
    data, unknown = ios_licenses(swift_checkouts, swift_resolved)
    if unknown:
        print("Unrecognised license (add a signature to scripts/go-licenses.py):", *unknown, sep="\n  ", file=sys.stderr)
        return 1
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(data, indent=1) + "\n")
    print(f"go-licenses: {len(data['libraries'])} libraries -> {out}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--ios", type=Path, metavar="OUT", help="write the iOS licenses JSON instead")
    parser.add_argument("--swift-checkouts", type=Path, help="Xcode's SourcePackages/checkouts directory")
    parser.add_argument("--swift-resolved", type=Path, help="Package.resolved, for the Swift package versions")
    args = parser.parse_args()
    if args.ios:
        return write_ios(args.ios, args.swift_checkouts, args.swift_resolved)

    modules = linked_modules()
    definitions = {file_name("std"): stdlib_definition()}
    unknown = []
    for module in modules:
        licenses = detect_licenses(Path(module["dir"]))
        if not licenses:
            unknown.append(module["path"])
            continue
        definitions[file_name(module["path"])] = definition(module, licenses)
    if unknown:
        print("Unrecognised license (add a signature to scripts/go-licenses.py):", *unknown, sep="\n  ", file=sys.stderr)
        return 1

    OUT.mkdir(parents=True, exist_ok=True)
    for stale in OUT.glob(PREFIX + "*.json"):
        stale.unlink()
    for name, data in definitions.items():
        (OUT / name).write_text(json.dumps(data, indent=2) + "\n")
    print(f"go-licenses: {len(modules)} modules + the standard library -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
