#!/usr/bin/env python3
"""Declares the Go core's modules to the AboutLibraries Gradle plugin.

Gradle cannot see inside the gomobile AAR, so the "Open-source licenses" screen would only list
the Android dependencies. This lists every module actually linked into the Android Go core
(`go list -deps` for the bound package, with the Android build constraints), detects each one's
license from its LICENSE/COPYING file in the module cache, and writes one library definition per
module, plus one for the Go standard library:

  app/aboutlibraries/libraries/go-<module>.json   (gitignored, regenerated by build.sh)

Fails when a module's license cannot be recognised, so a new dependency is never listed without
its license.

Usage: scripts/go-licenses.py
"""
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GO_DIR = ROOT / "go"
OUT = ROOT / "app/aboutlibraries/libraries"
PREFIX = "go-"
# The bound package, plus the gobind runtime gomobile links next to it.
PACKAGES = ["./ichorgo", "golang.org/x/mobile/bind/seq"]
ANDROID_ENV = {"GOOS": "android", "GOARCH": "arm64", "CGO_ENABLED": "1"}
LICENSE_FILES = re.compile(r"^(LICEN[CS]E|COPYING)(\.md|\.txt)?$", re.IGNORECASE)

# SPDX id -> phrases that must all appear in the license text (whitespace-normalised, lowercase).
# Order matters: the first match wins, so the more specific BSD-3 precedes BSD-2.
SIGNATURES = [
    ("Apache-2.0", ["apache license", "version 2.0"]),
    ("MPL-2.0", ["mozilla public license", "version 2.0"]),
    ("BSD-3-Clause", ["redistribution and use in source and binary forms", "to endorse or promote products derived"]),
    ("BSD-2-Clause", ["redistribution and use in source and binary forms"]),
    ("MIT", ["permission is hereby granted, free of charge"]),
    ("ISC", ["permission to use, copy, modify, and/or distribute this software for any purpose"]),
]


def go(*args: str) -> str:
    env = {**os.environ, **ANDROID_ENV}
    return subprocess.run(["go", *args], cwd=GO_DIR, env=env, check=True, capture_output=True, text=True).stdout


def linked_modules() -> list[dict]:
    template = "{{with .Module}}{{if not .Main}}{{.Path}}\t{{.Version}}\t{{.Dir}}{{end}}{{end}}"
    rows = {line for line in go("list", "-deps", "-f", template, *PACKAGES).splitlines() if line}
    modules = [dict(zip(("path", "version", "dir"), row.split("\t"))) for row in rows]
    return sorted(modules, key=lambda m: m["path"])


def detect_licenses(module_dir: Path) -> list[str]:
    texts = [f.read_text(errors="replace") for f in sorted(module_dir.iterdir()) if LICENSE_FILES.match(f.name)]
    found = []
    for text in texts:
        normalised = " ".join(text.lower().split())
        spdx = next((spdx for spdx, phrases in SIGNATURES if all(p in normalised for p in phrases)), None)
        if spdx and spdx not in found:
            found.append(spdx)
    return found


def source_url(path: str) -> str:
    if path.startswith("golang.org/x/"):
        return "https://cs.opensource.google/go/x/" + path.removeprefix("golang.org/x/").split("/")[0]
    return "https://pkg.go.dev/" + path


def definition(module: dict, licenses: list[str]) -> dict:
    return {
        "uniqueId": module["path"],
        "artifactVersion": module["version"],
        "name": module["path"],
        "description": "Go module compiled into the app's core library.",
        "website": source_url(module["path"]),
        "licenses": licenses,
    }


def stdlib_definition() -> dict:
    return {
        "uniqueId": "go.dev/std",
        "artifactVersion": go("env", "GOVERSION").strip().removeprefix("go"),
        "name": "Go standard library",
        "description": "The Go runtime and standard library, compiled into the app's core library.",
        "website": "https://go.dev",
        "organization": {"name": "The Go Authors", "url": "https://go.dev"},
        "licenses": ["BSD-3-Clause"],
    }


def file_name(path: str) -> str:
    return PREFIX + re.sub(r"[^A-Za-z0-9]+", "-", path).strip("-").lower() + ".json"


def main() -> int:
    modules = linked_modules()
    definitions = {file_name("std"): stdlib_definition()}
    unknown = []
    for module in modules:
        licenses = detect_licenses(Path(module["dir"]))
        if not licenses:
            unknown.append(module["path"])
            continue
        definitions[file_name(module["path"])] = definition(module, licenses)
    if unknown:
        print("Unrecognised license (add a signature to scripts/go-licenses.py):", *unknown, sep="\n  ", file=sys.stderr)
        return 1

    OUT.mkdir(parents=True, exist_ok=True)
    for stale in OUT.glob(PREFIX + "*.json"):
        stale.unlink()
    for name, data in definitions.items():
        (OUT / name).write_text(json.dumps(data, indent=2) + "\n")
    print(f"go-licenses: {len(modules)} modules + the standard library -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
